version: '2'
services:
  zookeeper:
    build: ../zookeeper-docker
    ports:
      - "2181:2181"
   networks:
     - kafka

  kafka:
    build: ../kafka-docker
    depends_on:
      - zookeeper
    ports:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
   networks:
     - kafka



networks:
  kafka:
    driver: overlay
